# Site Settings
title: "Ricard Penalver"
email: ricard@example.com
description: "Desarrollador y profesional tecnológico"
baseurl: ""
url: "https://ricardpenalver.vercel.app"

# Theme
theme: minimal-mistakes-jekyll

# Author
author:
  name: "Ricard Penalver"
  bio: "Desarrollador apasionado por la tecnología y la innovación"
  location: "España"
  email: "ricard@example.com"

# Defaults for posts and pages
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# Minimal Mistakes theme settings
minimal_mistakes_skin: "default"

# Navigation
navigation:
  - title: "Inicio"
    url: /
  - title: "Acerca de"
    url: /about/
  - title: "Proyectos"
    url: /projects/
  - title: "Blog"
    url: /blog/
  - title: "Contacto"
    url: /contact/