# Site Settings
title: "Ricard Penalver"
email: ricard@example.com
description: "Desarrollador y profesional tecnológico"
baseurl: ""
url: "https://ricardpenalver.github.io"

# Theme
remote_theme: "daattali/beautiful-jekyll@5.0.0"

# Plugins compatibles con GitHub Pages
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-remote-theme

# Author
author:
  name: "Ricard Penalver"
  bio: "Desarrollador apasionado por la tecnología y la innovación"
  location: "España"
  email: "ricard@example.com"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ricardpenalver"

# Beautiful Jekyll theme settings
avatar: "/assets/images/profile.jpg"
show-avatar: true
show-social-links: true
show-email: true
show-phone: false
show-address: false

# Social links
social-links:
  github: ricardpenalver
  email: ricard@example.com
  linkedin: # tu-linkedin
  twitter: # tu-twitter
  facebook: # tu-facebook
  instagram: # tu-instagram

# Navigation
navbar-links:
  Inicio: /
  Acerca de: /about/
  Proyectos: /projects/
  Blog: /blog/
  Contacto: /contact/

# Footer
footer-links:
  github: ricardpenalver
  email: ricard@example.com

# Pagination
paginate: 5
paginate_path: /blog/page:num/

# Comments (opcional)
comments:
  provider: false

# Analytics (opcional)
google-analytics: # tu-google-analytics-id