# Site Settings
title: "Ricard Penalver"
email: ricard@example.com
description: "Desarrollador y profesional tecnológico"
baseurl: ""
url: "https://ricardpenalver.github.io"

# Theme
theme: minima

# Plugins compatibles con GitHub Pages
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Author
author:
  name: "Ricard Penalver"
  bio: "Desarrollador apasionado por la tecnología y la innovación"
  location: "España"
  email: "ricard@example.com"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ricardpenalver"

# Defaults for posts and pages
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: pages
    values:
      layout: page

# Pagination
paginate: 5
paginate_path: /blog/page:num/

# Minima theme settings
social_links:
  github: ricardpenalver
  email: ricard@example.com